--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpzz/SellMe
build-by-default: true
branches:
- main
projects:
  SellMe:
    path: ""
    icon: 'sell.png'
    lint:
      phpstan: false
    libs:
      - src: CortexPE/Commando/Commando
        version:  ^3.0.0
        branch: PM4
      - src: muqsit/simplepackethandler/SimplePacketHandler
        version: ^0.1.2
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.1.2
...
